// Code generated by "stringer -type=ScriptState"; DO NOT EDIT.

package robolang

import "strconv"

const _ScriptState_name = "ScriptStatePendingScriptStateWaitingScriptStateFinishedScriptStateFailed"

var _ScriptState_index = [...]uint8{0, 18, 36, 55, 72}

func (i ScriptState) String() string {
	if i < 0 || i >= ScriptState(len(_ScriptState_index)-1) {
		return "ScriptState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScriptState_name[_ScriptState_index[i]:_ScriptState_index[i+1]]
}
